//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MilvaTemplate.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MilvaTemplate.Localization.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oturumunuz zaman aşımına uğradı..
        /// </summary>
        public static string AccountTimeOut {
            get {
                return ResourceManager.GetString("AccountTimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silindi.
        /// </summary>
        public static string ActionDELETE {
            get {
                return ResourceManager.GetString("ActionDELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eklendi.
        /// </summary>
        public static string ActionPOST {
            get {
                return ResourceManager.GetString("ActionPOST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncellendi.
        /// </summary>
        public static string ActionPUT {
            get {
                return ResourceManager.GetString("ActionPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Varolan veri kimliği ile aynı veri kimliğine sahip bir veri ekleyemezsiniz!.
        /// </summary>
        public static string AddingNewEntityWithExistsIdException {
            get {
                return ResourceManager.GetString("AddingNewEntityWithExistsIdException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} başarıyla eklendi..
        /// </summary>
        public static string AddSuccessMessage {
            get {
                return ResourceManager.GetString("AddSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En az bir tane rol seçmelisiniz..
        /// </summary>
        public static string AddUserRolesIsNullOrEmptyListExeption {
            get {
                return ResourceManager.GetString("AddUserRolesIsNullOrEmptyListExeption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaten sistemden çıkış yapılmış..
        /// </summary>
        public static string AlreadyLoggedOutMessage {
            get {
                return ResourceManager.GetString("AlreadyLoggedOutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem sırasında beklenmeyen bir hata oluştu lütfen tekrar deneyiniz. Sorun çözülmezse lütfen teknik ekip ile iletişime geçiniz..
        /// </summary>
        public static string AnErrorOccured {
            get {
                return ResourceManager.GetString("AnErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhangi bir {0} bulunamadı..
        /// </summary>
        public static string AnyEntityWasNotFound {
            get {
                return ResourceManager.GetString("AnyEntityWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulama başarıyla durduruldu..
        /// </summary>
        public static string AppStoppedSuccessfully {
            get {
                return ResourceManager.GetString("AppStoppedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bulunamadı..
        /// </summary>
        public static string CannotFoundMessage {
            get {
                return ResourceManager.GetString("CannotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilgilerinizi alamıyoruz. Lütfen tekrar giriş yapmayı deneyin..
        /// </summary>
        public static string CannotGetSignedInUserInfo {
            get {
                return ResourceManager.GetString("CannotGetSignedInUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veritabanındaki varsayılan verileri güncelleyemez veya silemezsiniz..
        /// </summary>
        public static string CannotUpdateOrDeleteDefaultRecord {
            get {
                return ResourceManager.GetString("CannotUpdateOrDeleteDefaultRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bulunamadı..
        /// </summary>
        public static string ControllersSingleObjectWasNotFound {
            get {
                return ResourceManager.GetString("ControllersSingleObjectWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silinecek herhangi bir {0} bulunamadı..
        /// </summary>
        public static string DeleteErrorMessage {
            get {
                return ResourceManager.GetString("DeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir ilişkisi olan verileri silmeye çalışıyorsunuz..
        /// </summary>
        public static string DeletingEntityWithRelationsException {
            get {
                return ResourceManager.GetString("DeletingEntityWithRelationsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz silme işlemi!.
        /// </summary>
        public static string DeletingInvalidEntityException {
            get {
                return ResourceManager.GetString("DeletingInvalidEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu özellik henüz kullanımda değil..
        /// </summary>
        public static string FeatureNotImplementedException {
            get {
                return ResourceManager.GetString("FeatureNotImplementedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen yüklemek için bir dosya seçiniz..
        /// </summary>
        public static string FileCannotBeEmpty {
            get {
                return ResourceManager.GetString("FileCannotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dosya boyutu çok büyük. Lütfen {0} MB veya daha küçük boyutlu bir dosya yükleyin..
        /// </summary>
        public static string FileIsTooBigMessage {
            get {
                return ResourceManager.GetString("FileIsTooBigMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arama kriterlerine uygun bir {0} bulunamadı..
        /// </summary>
        public static string FilteringErrorMessage {
            get {
                return ResourceManager.GetString("FilteringErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erişim izniniz yok..
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhangi bir {0} bulunamadı..
        /// </summary>
        public static string GetAllErrorMessage {
            get {
                return ResourceManager.GetString("GetAllErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} saat.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eşzamanlılık hatası, veri değiştirildi..
        /// </summary>
        public static string IdentityConcurrencyFailure {
            get {
                return ResourceManager.GetString("IdentityConcurrencyFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilinmeyen bir hata meydana geldi..
        /// </summary>
        public static string IdentityDefaultError {
            get {
                return ResourceManager.GetString("IdentityDefaultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu email hesabına sahip başka bir kullanıcı bulunuyor..
        /// </summary>
        public static string IdentityDuplicateEmail {
            get {
                return ResourceManager.GetString("IdentityDuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu rol zaten var..
        /// </summary>
        public static string IdentityDuplicateRoleName {
            get {
                return ResourceManager.GetString("IdentityDuplicateRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı adına sahip başka bir kullanıcı bulunuyor..
        /// </summary>
        public static string IdentityDuplicateUsername {
            get {
                return ResourceManager.GetString("IdentityDuplicateUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz email hesabı girdiniz..
        /// </summary>
        public static string IdentityInvalidEmail {
            get {
                return ResourceManager.GetString("IdentityInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz bir rol adı girdiniz..
        /// </summary>
        public static string IdentityInvalidRoleName {
            get {
                return ResourceManager.GetString("IdentityInvalidRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz kimlik bilgisi..
        /// </summary>
        public static string IdentityInvalidToken {
            get {
                return ResourceManager.GetString("IdentityInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz bir kullanıcı adı girdiniz..
        /// </summary>
        public static string IdentityInvalidUsername {
            get {
                return ResourceManager.GetString("IdentityInvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı zaten giriş yapmış..
        /// </summary>
        public static string IdentityLoginAlreadyAssociated {
            get {
                return ResourceManager.GetString("IdentityLoginAlreadyAssociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yanlış şifre girdiniz..
        /// </summary>
        public static string IdentityPasswordMismatch {
            get {
                return ResourceManager.GetString("IdentityPasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre en az bir rakam içermelidir..
        /// </summary>
        public static string IdentityPasswordRequiresDigit {
            get {
                return ResourceManager.GetString("IdentityPasswordRequiresDigit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre en az bir küçük harf içermelidir..
        /// </summary>
        public static string IdentityPasswordRequiresLower {
            get {
                return ResourceManager.GetString("IdentityPasswordRequiresLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola en az bir alfanümerik karakter içermelidir..
        /// </summary>
        public static string IdentityPasswordRequiresNonAlphanumeric {
            get {
                return ResourceManager.GetString("IdentityPasswordRequiresNonAlphanumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola en az bir özel karakter içermelidir..
        /// </summary>
        public static string IdentityPasswordRequiresUniqueChars {
            get {
                return ResourceManager.GetString("IdentityPasswordRequiresUniqueChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre en az bir büyük harf içermelidir..
        /// </summary>
        public static string IdentityPasswordRequiresUpper {
            get {
                return ResourceManager.GetString("IdentityPasswordRequiresUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Şifre uzunluğu çok kısa..
        /// </summary>
        public static string IdentityPasswordTooShort {
            get {
                return ResourceManager.GetString("IdentityPasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurtarma başarısız oldu..
        /// </summary>
        public static string IdentityRecoveryCodeRedemptionFailed {
            get {
                return ResourceManager.GetString("IdentityRecoveryCodeRedemptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı işlemlerinde bir hata gerçekleşti..
        /// </summary>
        public static string IdentityResultException {
            get {
                return ResourceManager.GetString("IdentityResultException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcının zaten bir şifresi var..
        /// </summary>
        public static string IdentityUserAlreadyHasPassword {
            get {
                return ResourceManager.GetString("IdentityUserAlreadyHasPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı zaten bu role atanmış..
        /// </summary>
        public static string IdentityUserAlreadyInRole {
            get {
                return ResourceManager.GetString("IdentityUserAlreadyInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı için kilitleme etkinleştirilmedi..
        /// </summary>
        public static string IdentityUserLockoutNotEnabled {
            get {
                return ResourceManager.GetString("IdentityUserLockoutNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı bu role atanmamış..
        /// </summary>
        public static string IdentityUserNotInRole {
            get {
                return ResourceManager.GetString("IdentityUserNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu mail adresine sahip kullanıcı yok..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir &apos;listelenecek eleman&apos; sayısı giriniz..
        /// </summary>
        public static string InvalidItemRangeException {
            get {
                return ResourceManager.GetString("InvalidItemRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz lisans!.
        /// </summary>
        public static string InvalidLicenceException {
            get {
                return ResourceManager.GetString("InvalidLicenceException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş bilgileriniz doğrulanamadı..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girilen {0} sayısal değeri bu işlem için geçersiz bir değerdir..
        /// </summary>
        public static string InvalidNumericValueException {
            get {
                return ResourceManager.GetString("InvalidNumericValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen sipariş tipi ile uyuşan herhangi bir sipariş tipi bulunamadı..
        /// </summary>
        public static string InvalidOrderType {
            get {
                return ResourceManager.GetString("InvalidOrderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir sayfa numarası giriniz..
        /// </summary>
        public static string InvalidPageIndexException {
            get {
                return ResourceManager.GetString("InvalidPageIndexException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veride hata bulundu. Lütfen Milvasoft yetkilileri ile iletişime geçiniz..
        /// </summary>
        public static string InvalidParameterException {
            get {
                return ResourceManager.GetString("InvalidParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz şifre girildi..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlemi yapmaya çalıştığınız verilerin ilişkili olduğu bir veri bulunmakta..
        /// </summary>
        public static string InvalidRelatedProcess {
            get {
                return ResourceManager.GetString("InvalidRelatedProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seçilen vardiya tipi ile uyuşan herhangi bir vardiya tipi bulunamadı..
        /// </summary>
        public static string InvalidShiftType {
            get {
                return ResourceManager.GetString("InvalidShiftType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu kullanıcı adına sahip kullanıcı yok..
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string LocalizedEmail {
            get {
                return ResourceManager.GetString("LocalizedEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İsim.
        /// </summary>
        public static string LocalizedName {
            get {
                return ResourceManager.GetString("LocalizedName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parola.
        /// </summary>
        public static string LocalizedPassword {
            get {
                return ResourceManager.GetString("LocalizedPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı.
        /// </summary>
        public static string LocalizedUser {
            get {
                return ResourceManager.GetString("LocalizedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı.
        /// </summary>
        public static string LocalizedUserName {
            get {
                return ResourceManager.GetString("LocalizedUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site adresi.
        /// </summary>
        public static string LocalizedWebSiteAddress {
            get {
                return ResourceManager.GetString("LocalizedWebSiteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art arda başarısız giriş denemesi yaptığınızdan dolayı hesabınız kilitlenmiştir. {0} sonra tekrar deneyin..
        /// </summary>
        public static string Locked {
            get {
                return ResourceManager.GetString("Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} geçersiz deneme sonucunda oturum kilitlenecektir..
        /// </summary>
        public static string LockWarning {
            get {
                return ResourceManager.GetString("LockWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başka bir işletmede bu hesap ile oturum açılmış. Şifrenizi değiştirmek için lütfen mail kutunuzu kontrol edin. Diğer oturumunuz kapatılacaktır..
        /// </summary>
        public static string LoggedInOtherInstitution {
            get {
                return ResourceManager.GetString("LoggedInOtherInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir problem oluştu. Hata mesajı: {0}.
        /// </summary>
        public static string LoginCustomerErrorMessageFromAPI {
            get {
                return ResourceManager.GetString("LoginCustomerErrorMessageFromAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir hata oluştu. Hata, yanlış parametre veya url ile ilgili olabilir. Lütfen istek parametrelerini veya url&apos;yi kontrol edin..
        /// </summary>
        public static string MiddlewareGeneralErrorMessage {
            get {
                return ResourceManager.GetString("MiddlewareGeneralErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beklenmeyen bir hata ile karşılaşıldı lütfen tekrar deneyiniz. Eğer sorun çözülmezse lütfen Milvasoft teknik ekibi ile iletişime geçiniz..
        /// </summary>
        public static string MilvaBaseException {
            get {
                return ResourceManager.GetString("MilvaBaseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bir hata oluştu. Hata, yanlış parametre veya url ile ilgili olabilir. Lütfen istek parametrelerini veya url&apos;yi kontrol edin.
        /// </summary>
        public static string MilvaUserFriendlyException {
            get {
                return ResourceManager.GetString("MilvaUserFriendlyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz model değeri. Lütfen geçerli bir model değeri giriniz..
        /// </summary>
        public static string MilvaValidationException {
            get {
                return ResourceManager.GetString("MilvaValidationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir {0} girin..
        /// </summary>
        public static string MinDecimalValueException {
            get {
                return ResourceManager.GetString("MinDecimalValueException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dakika.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Header bilgisini giriniz!.
        /// </summary>
        public static string MissingHeaderException {
            get {
                return ResourceManager.GetString("MissingHeaderException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girişiniz herhangi bir sebepten dolayı engellenmiş gözüküyor. Bunun bir yanlışlık olduğunu düşünüyorsanız lütfen Milvasoft teknik ekibi ile iletişime geçin..
        /// </summary>
        public static string NotAllowed {
            get {
                return ResourceManager.GetString("NotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bazı verileri eksik gönderdiniz. Eğer bir hata yapmadığınızı düşünüyorsanız lütfen Milvasoft teknik ekibi ile iletişime geçin..
        /// </summary>
        public static string NullParameterException {
            get {
                return ResourceManager.GetString("NullParameterException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uygulamanızın sürümü eski. Kullanmaya devam etmek için lütfen uygulamanın güncellenmesini bekleyin..
        /// </summary>
        public static string OldVersion {
            get {
                return ResourceManager.GetString("OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstenen sayfa sayısı oluşan sayfa sayısından fazla. Maksimum sayfa sayısı {0} olmalıdır..
        /// </summary>
        public static string OutOfRangePageCountMessage {
            get {
                return ResourceManager.GetString("OutOfRangePageCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir değer girin..
        /// </summary>
        public static string PleaseEnterAValidValue {
            get {
                return ResourceManager.GetString("PleaseEnterAValidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir kullanıcı bilgisi girin..
        /// </summary>
        public static string PleaseEnterValidUserInfo {
            get {
                return ResourceManager.GetString("PleaseEnterValidUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, minimum karakter sınırının altında. Lütfen en az {1} karakter girin..
        /// </summary>
        public static string PreventStringInjectionBellowMin {
            get {
                return ResourceManager.GetString("PreventStringInjectionBellowMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, geçersiz kelime içeriyor..
        /// </summary>
        public static string PreventStringInjectionContainsForbiddenWordError {
            get {
                return ResourceManager.GetString("PreventStringInjectionContainsForbiddenWordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1} ile {2} aralığında bir karakter uzunluğuna sahip olmalıdır..
        /// </summary>
        public static string PreventStringInjectionLengthResultNotTrue {
            get {
                return ResourceManager.GetString("PreventStringInjectionLengthResultNotTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen maksimum karakter uzunluğu için geçerli bir değer girin..
        /// </summary>
        public static string PreventStringInjectionMaxLengthException {
            get {
                return ResourceManager.GetString("PreventStringInjectionMaxLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Girdiğiniz minimum değer({0}) maksimum değerden({1}) büyük. Lütfen geçerli bir değer aralığı girin..
        /// </summary>
        public static string PreventStringInjectionMinLengthBigThanMaxLengthException {
            get {
                return ResourceManager.GetString("PreventStringInjectionMinLengthBigThanMaxLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen minimum karakter uzunluğu için geçerli bir değer girin..
        /// </summary>
        public static string PreventStringInjectionMinLengthException {
            get {
                return ResourceManager.GetString("PreventStringInjectionMinLengthException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarıyla gerçekleşti..
        /// </summary>
        public static string ProcessCompletedSuccessfully {
            get {
                return ResourceManager.GetString("ProcessCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} girilmesi zorunludur..
        /// </summary>
        public static string PropertyIsRequired {
            get {
                return ResourceManager.GetString("PropertyIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, düzgün formatta değil. Lütfen şu formatta girin: {1}.
        /// </summary>
        public static string RegexErrorMessage {
            get {
                return ResourceManager.GetString("RegexErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7975-777666.
        /// </summary>
        public static string RegexExampleAccountNo {
            get {
                return ResourceManager.GetString("RegexExampleAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1234 1234 1234 1234.
        /// </summary>
        public static string RegexExampleCreditCardNo {
            get {
                return ResourceManager.GetString("RegexExampleCreditCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ornek@milvasoft.com.
        /// </summary>
        public static string RegexExampleEmail {
            get {
                return ResourceManager.GetString("RegexExampleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33 0006 1005 1978 6457 8413 26.
        /// </summary>
        public static string RegexExampleIBANNO {
            get {
                return ResourceManager.GetString("RegexExampleIBANNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tr-TR.
        /// </summary>
        public static string RegexExampleIsoCode {
            get {
                return ResourceManager.GetString("RegexExampleIsoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0 505 010 79 85.
        /// </summary>
        public static string RegexExamplePhoneNumber {
            get {
                return ResourceManager.GetString("RegexExamplePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^((\d{4})-(\d{6}))$.
        /// </summary>
        public static string RegexPatternAccountNo {
            get {
                return ResourceManager.GetString("RegexPatternAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^((\d{4}) (\d{4}) (\d{4}) (\d{4}))$.
        /// </summary>
        public static string RegexPatternCreditCardNo {
            get {
                return ResourceManager.GetString("RegexPatternCreditCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^\w+([-+.&apos;]\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$.
        /// </summary>
        public static string RegexPatternEmail {
            get {
                return ResourceManager.GetString("RegexPatternEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^((\d{2}) (\d{4}) (\d{4}) (\d{4}) (\d{4}) (\d{4}) (\d{2}))$.
        /// </summary>
        public static string RegexPatternIBANNO {
            get {
                return ResourceManager.GetString("RegexPatternIBANNO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^[a-z]{2}-[a-zA-Z]{2}$.
        /// </summary>
        public static string RegexPatternIsoCode {
            get {
                return ResourceManager.GetString("RegexPatternIsoCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ^(0 (\d{3}) (\d{3}) (\d{2}) (\d{2}))$.
        /// </summary>
        public static string RegexPatternPhoneNumber {
            get {
                return ResourceManager.GetString("RegexPatternPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İki faktörlü doğrulama gerekli..
        /// </summary>
        public static string RequiresTwoFactor {
            get {
                return ResourceManager.GetString("RequiresTwoFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı rolleri başarıyla güncellendi..
        /// </summary>
        public static string RolesUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("RolesUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} saniye.
        /// </summary>
        public static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla giriş yapıldı..
        /// </summary>
        public static string SuccessfullyLoginMessage {
            get {
                return ResourceManager.GetString("SuccessfullyLoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Başarıyla çıkış yapıldı..
        /// </summary>
        public static string SuccessfullyLoguotMessage {
            get {
                return ResourceManager.GetString("SuccessfullyLoguotMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İşlem başarıyla gerçekleşti..
        /// </summary>
        public static string SuccessfullyOperationMessage {
            get {
                return ResourceManager.GetString("SuccessfullyOperationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token üretilemedi..
        /// </summary>
        public static string TokenCouldNotBeGenerated {
            get {
                return ResourceManager.GetString("TokenCouldNotBeGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geçersiz kimlik bilgileri nedeniyle erişim engellendi..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giriş yapılamadı. Bilinmeyen bir problem oluştu..
        /// </summary>
        public static string UnknownLoginProblemMessage {
            get {
                return ResourceManager.GetString("UnknownLoginProblemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çıkış yapılamadı. Bilinmeyen bir problem oluştu..
        /// </summary>
        public static string UnknownLogoutProblemMessage {
            get {
                return ResourceManager.GetString("UnknownLogoutProblemMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bu dosya türü desteklenmiyor. Lütfen geçerli bir dosya türü yükleyin. Desteklenen dosya türleri: {0}..
        /// </summary>
        public static string UnsupportedFileTypeMessage {
            get {
                return ResourceManager.GetString("UnsupportedFileTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} başarıyla güncellendi..
        /// </summary>
        public static string UpdateSuccessMessage {
            get {
                return ResourceManager.GetString("UpdateSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Güncelleme işlemi başarısız..
        /// </summary>
        public static string UpdatingInvalidEntityException {
            get {
                return ResourceManager.GetString("UpdatingInvalidEntityException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rol bulunamadı..
        /// </summary>
        public static string UserRoleAddNotFoundException {
            get {
                return ResourceManager.GetString("UserRoleAddNotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcıya ait aktif bir rol bulunamadı..
        /// </summary>
        public static string UserRoleNotFound {
            get {
                return ResourceManager.GetString("UserRoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail adresi en fazla {0} karakter içerebilir..
        /// </summary>
        public static string UserValidationEmailLength {
            get {
                return ResourceManager.GetString("UserValidationEmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı en az {0}, en fazla {1} karakter içerebilir..
        /// </summary>
        public static string UserValidationUserNameLength {
            get {
                return ResourceManager.GetString("UserValidationUserNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kullanıcı adı sayısal bir karakter ile başlayamaz..
        /// </summary>
        public static string UserValidationUserNameNumberStartWith {
            get {
                return ResourceManager.GetString("UserValidationUserNameNumberStartWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen gerekli olan bütün parametreleri eksiksiz girin..
        /// </summary>
        public static string ValidationIdParameterGeneralError {
            get {
                return ResourceManager.GetString("ValidationIdParameterGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lütfen geçerli bir {0} seçin..
        /// </summary>
        public static string ValidationIdPropertyError {
            get {
                return ResourceManager.GetString("ValidationIdPropertyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} bulunamadı..
        /// </summary>
        public static string WantedWasNotFound {
            get {
                return ResourceManager.GetString("WantedWasNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstenen sayfa sayısı, oluşturulan sayfa sayfasından fazla. Maksimum sayfa sayısı {0} olmalıdır..
        /// </summary>
        public static string WrongPaginationParamsException {
            get {
                return ResourceManager.GetString("WrongPaginationParamsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstenen kayıt sayısının sayısı 0 veya daha az olamaz. İstenen kayıt sayısı 0&apos;dan büyük olmalıdır..
        /// </summary>
        public static string WrongRequestedItemCount {
            get {
                return ResourceManager.GetString("WrongRequestedItemCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to İstenen sayfa sayısı 0 olamaz. Sayfa sayısı 0&apos;dan büyük olmalıdır..
        /// </summary>
        public static string WrongRequestedPageNumber {
            get {
                return ResourceManager.GetString("WrongRequestedPageNumber", resourceCulture);
            }
        }
    }
}
